name: EnthusiaDonorNPCs
main: com.enthusiasmpvp.donornpcs.EnthusiaDonorNPCsPlugin
version: 1.0.4
api-version: '1.21'
depend:
  - PlaceholderAPI
softdepend:
  - Citizens
  - FancyNpcs
commands:
  EnthusiaDonorNPCs:
    description: Main command for EnthusiaDonorNPCs
    usage: /EnthusiaDonorNPCs <reload|update|status>
    aliases:
      - donornpcs
      - ednpcs
permissions:
  enthusiadonornpcs.admin:
    description: Allows use of EnthusiaDonorNPCs admin commands
    default: op
